SELECT ROUND(SUM(TIV_2016),2) AS TIV_2016 FROM INSURANCE WHERE TIV_2015 IN
    (SELECT TIV_2015 FROM INSURANCE GROUP BY 1 HAVING COUNT(*)>1)
        AND CONCAT(LAT,LON) IN (SELECT CONCAT(LAT,LON) FROM INSURANCE GROUP BY LAT,LON HAVING COUNT(*)=1);
